- name: "Run all role tasks for Ubuntu"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    udisks_conflict_package_uninstall_list: "{{ udisks_ubuntu_conflict_package_uninstall_list }}"
    udisks_main_package_name: "{{ udisks_ubuntu_main_package_name }}"
    udisks_exfat_filesystems_package_list: "{{ udisks_ubuntu_exfat_filesystems_package_list }}"
    udisks_ntfs_filesystems_package: "{{ udisks_ubuntu_ntfs_filesystems_package }}"
    udisks_ext2_ext4_filesystems_package: "{{ udisks_ubuntu_ext2_ext4_filesystems_package }}"
    udisks_hfs_filesystems_package: "{{ udisks_ubuntu_hfs_filesystems_package }}"
    udisks_xfs_filesystems_package: "{{ udisks_ubuntu_xfs_filesystems_package }}"
    udisks_mtp_filesystems_package: "{{ udisks_ubuntu_mtp_filesystems_package }}"
  when: ansible_distribution == "Ubuntu"

- name: "Run all role tasks for Arch Linux"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    udisks_conflict_package_uninstall_list: "{{ udisks_archlinux_conflict_package_uninstall_list }}"
    udisks_main_package_name: "{{ udisks_archlinux_main_package_name }}"
    udisks_exfat_filesystems_package_list: "{{ udisks_archlinux_exfat_filesystems_package_list }}"
    udisks_ntfs_filesystems_package: "{{ udisks_archlinux_ntfs_filesystems_package }}"
    udisks_ext2_ext4_filesystems_package: "{{ udisks_archlinux_ext2_ext4_filesystems_package }}"
    udisks_hfs_filesystems_package: "{{ udisks_archlinux_hfs_filesystems_package }}"
    udisks_xfs_filesystems_package: "{{ udisks_archlinux_xfs_filesystems_package }}"
    udisks_mtp_filesystems_package: "{{ udisks_archlinux_mtp_filesystems_package }}"
  when: ansible_os_family == "Archlinux"

- name: "Run all role tasks for FreeBSD"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    udisks_conflict_package_uninstall_list: "{{ udisks_freebsd_conflict_package_uninstall_list }}"
    udisks_main_package_name: "{{ udisks_freebsd_main_package_name }}"
    udisks_exfat_filesystems_package_list: "{{ udisks_freebsd_exfat_filesystems_package_list }}"
    udisks_ntfs_filesystems_package: "{{ udisks_freebsd_ntfs_filesystems_package }}"
    udisks_ext2_ext4_filesystems_package: "{{ udisks_freebsd_ext2_ext4_filesystems_package }}"
    udisks_hfs_filesystems_package: "{{ udisks_freebsd_hfs_filesystems_package }}"
    udisks_xfs_filesystems_package: "{{ udisks_freebsd_xfs_filesystems_package }}"
    udisks_mtp_filesystems_package: "{{ udisks_freebsd_mtp_filesystems_package }}"
  when: ansible_os_family == "FreeBSD"

