# uninstall and disable other device auto-mounters
udisks_remove_other_device_auto_mounters: true

# when device auto-mounting enabled, support various filesystems
udisks_support_exfat_filesystems: true
udisks_support_ntfs_filesystems: true
udisks_support_ext2_ext4_filesystems: true
udisks_support_hfs_filesystems: false
udisks_support_xfs_filesystems: false
udisks_support_mtp_filesystems: false

