- name: "Install exFAT support packages: '{{ udisks_exfat_filesystems_package_list }}'"
  ansible.builtin.package:
    name: "{{ udisks_exfat_filesystems_package_list }}"
    state: present
  become: true
  become_user: root
  when: udisks_support_exfat_filesystems

- name: "Install NTFS R/W support package: '{{ udisks_ntfs_filesystems_package }}'"
  ansible.builtin.package:
    name: "{{ udisks_ntfs_filesystems_package }}"
    state: present
  become: true
  become_user: root
  when: udisks_support_ntfs_filesystems

- name: "Install ext2/ext4 support package: '{{ udisks_ext2_ext4_filesystems_package }}'"
  ansible.builtin.package:
    name: "{{ udisks_ext2_ext4_filesystems_package }}"
    state: present
  become: true
  become_user: root
  when: udisks_support_ext2_ext4_filesystems

- name: "Install HFS support package: '{{ udisks_hfs_filesystems_package }}'"
  ansible.builtin.package:
    name: "{{ udisks_hfs_filesystems_package }}"
    state: present
  become: true
  become_user: root
  when: udisks_support_hfs_filesystems

- name: "Install XFS support package: '{{ udisks_xfs_filesystems_package }}'"
  ansible.builtin.package:
    name: "{{ udisks_xfs_filesystems_package }}"
    state: present
  become: true
  become_user: root
  when: udisks_support_xfs_filesystems

- name: "Install MTP support package: '{{ udisks_mtp_filesystems_package }}'"
  ansible.builtin.package:
    name: "{{ udisks_mtp_filesystems_package }}"
    state: present
  become: true
  become_user: root
  when: udisks_support_mtp_filesystems

